[agent]
  interval = "10s"
  flush_interval = "10s"
  hostname = "bruno-pc"

[[outputs.influxdb_v2]]
  # Prueba local: host.docker.internal -> el host (donde corre el docker-compose de la "VM" simulada).
  # Cuando se despliegue de verdad: cambiar por la IP de Tailscale de la VM, ej. http://100.112.249.84:8086
  urls = ["http://host.docker.internal:8086"]
  token = "soa-token-2026"
  organization = "soa"
  bucket = "metrics"

[[inputs.cpu]]
  percpu = false
  totalcpu = true

[[inputs.mem]]
