[agent]
  interval = "10s"
  flush_interval = "10s"
  hostname = "bruno-pc"

[[outputs.influxdb_v2]]
  # IP de Tailscale real de la VM (2020bigdata7). Antes, en pruebas locales, era host.docker.internal.
  urls = ["http://100.102.222.91:8086"]
  token = "soa-token-2026"
  organization = "soa"
  bucket = "metrics"

[[inputs.cpu]]
  percpu = false
  totalcpu = true

[[inputs.mem]]
