services:
  telegraf:
    image: telegraf:1.32
    container_name: bruno_telegraf
    restart: unless-stopped
    hostname: bruno-pc
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/hostfs:ro
    environment:
      HOST_PROC: /host/proc
      HOST_SYS: /host/sys
      HOST_MOUNT_PREFIX: /hostfs
    extra_hosts:
      - "host.docker.internal:host-gateway"  # para llegar al InfluxDB "de la VM" en la prueba local
